name: test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  node:
    strategy:
      matrix:
        environment:
        - type: node
          version: 18.x
        - type: node
          version: 20.x
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.environment.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.environment.version }}
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript
        run: node_modules/.bin/tsc --noEmit
      - name: Run test
        run: npm run test
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4
      - name: Run test
        run: deno run -A bin/test.ts
